### ISSUE TITLE
Rendre les build plus résilients vis-à-vis de la récupération de données sur data.gouv.fr

### ISSUE THREAD

**Issue by skelz0r** [betagouv/api.gouv.fr#1143]
Lors de build en local et sur la CI (`npm run build`) aujourd'hui nous avons eu plusieurs erreurs:

```
FetchError: invalid json response body at https://www.data.gouv.fr/api/1/datasets/53ca2e62a3a7294a1ddd784b reason: Unexpected token I in JSON at position 0
```

Le souci semble être une indisponibilité temporaire de data.gouv, ce qui faisait que le build plantait.

Il y a plusieurs approches possibles:

1. Mettre des retry exponentiels avec limit sur ces fetchs + un throw final human readable du genre "data.gouv.fr unreachable, please try again later"
2. Ne plus dépendre de cette dépendance externe pour construire le site

Il y a certainement d'autres pistes, à voir. A chaud je dirais que la 1. est pas mal

Resources/contexte: https://mattermost.incubateur.net/betagouv/pl/oj8qjyowfjbmfkxkt4f6syhmge

**Comment by XavierJp** [comment]
J'ajouterais une 3e option, car le but est uniquement de détecter les 404 : 
3. uniquement fail le build si status === 404, ignorer la condition sur datagouv sinon.

**Comment by XavierJp** [comment]
Facile a implémenter

**Comment by skelz0r** [comment]
Pour moi ici c'était vraiment un problème temporaire de data.gouv, la 404 à priori c'est "permanent" (et je suis d'accord ça devrait être géré).

Je ne suis pas sûr que gérer le 404 résolve ce problème ici btw.

**Comment by XavierJp** [comment]
Ah yes me suis mal exprimé.

En gros je propose : 
- 404 : permanent = lien mort, c'est un peu voulu que le build pete c'est a ca que servait ce check
- 2xx ou 5xx peut importe, on peu ignorer

**Comment by skelz0r** [comment]
N'ayant pas la connaissance métier je ne peux pas m'exprimer sur le `5XX peu importe, on peut ignorer`, mais du coup de ce que je comprends de ton message c'est que l'on n'a pas besoin des infos de data.gouv pour build ? Dans ce cas là pourquoi on les fetch ..?

**Comment by XavierJp** [comment]
L'info qu'on souhaite obtenir de datagouv, c'est est ce que cette ressource existe encore. 
En effect certain(e) FD avaient / ont l'habitude de supprimer et republier les jeux de donnée. 

A l'époque c'était ce que j'avais mis en place  pour être certain de ne pas déployer des liens morts. Si datagouv retourne 404, c'est que tu dois mettre des liens à jours.

Mais :  
- à l'époque j'étais bien plus impliqué sur apigouv et j'acceptais cette situation un peu bancale (la dépendance a datagouv ne devrait pas pouvoir péter le build) car je savais que je pourrais la contourner si nécessaire
- datagouv a peut etre introduit des liens permanents depuis, qui éviteraient pas mal d'emm***
