### ISSUE TITLE
Erreur 400 lors de la recherche des numéros de rue compris entre 10 à 99.

### ISSUE THREAD

**Issue by farochell** [betagouv/api.gouv.fr#1194]
Il semble que lorsque l’on utilise l'API via un champ auto-complete pour rechercher des adresses avec des numéros de rue supérieurs compris entre 10 et 99 , l’API  renvoie une erreur 400.
![image010](https://github.com/betagouv/api.gouv.fr/assets/15414997/82c1b7ad-b04e-4db4-9b70-1d79c621513c)
![image005](https://github.com/betagouv/api.gouv.fr/assets/15414997/56ee273b-a3cc-4225-821d-1bd6f2e2774c)
![image004](https://github.com/betagouv/api.gouv.fr/assets/15414997/58d63147-dd8a-4bbe-b85a-20a607d55583)

**Comment by skelz0r** [comment]
Bonjour,

api.gouv.fr n'est qu'un catalogue d'API et ne s'occupe pas de gérer les bugs et fonctionnalités des API listées.

Pour reporter votre problème je vous invite à contacter l'équipe via leur page API https://api.gouv.fr/les-api/base-adresse-nationale
