### ISSUE TITLE
Être notifié de l'ajout d'une API

### ISSUE THREAD

**Issue by ThibautGery** [betagouv/api.gouv.fr#126]
retour de reddit

>  Il y a un autre moyen de suivre l'avancement, les ajouts d'API, tout ça

Proposition
- flux RSS
- newsletter

**Comment by MattiSG** [comment]
La newsletter est le plus petit dénominateur commun, il en faut probablement une.

**Comment by Canop** [comment]
C'est moi qui ai fait ce commentaire sur reddit donc je plussoie...

La newsletter est une solution possible, mais ça vient souvent avec une grosse couche de formalisme.  Et il me semble qu'une annonce doit pouvoir s'accompagner d'une discussion (usages, intentions, etc.).

Des solutions légères (non exclusives les unes des autres) pourraient être:

* une liste de diffusion mail (souvent un peu lourd, surtout si une annonce entraîne des discussions)
* des salles de chat (ça [je peux fournir](https://github.com/Canop/miaou) ;))
* un sous-reddit (ça me semble présenter pas mal d'avantages)

Les flux RSS et tweets peuvent venir en complément mais ils ne peuvent remplacer, ils ne donnent que des alertes sans contenu.

**Comment by MattiSG** [comment]
Cool, merci @Canop de détailler ton intention !  :)

Si je comprends bien ton idée à travers les exemples que tu donnes, il s'agit d'espaces de discussion _autour_ des annonces. Je ne suis pas certain que ce soit réellement une fonctionnalité du catalogue api.gouv.fr lui-même. Comme tu le dis, un chat, Reddit, ou [un forum](https://forum.etalab.gouv.fr) feront très bien l'affaire, sans forcer à concentrer la discussion sur un outil spécifique.

Les usages sont listés sur chaque page de description d'API, et je doute qu'on puisse rendre suffisamment lisibles les « intentions » de réutilisation pour que ça vaille le coup de les référencer.

Il me semble pertinent de pouvoir être notifié des nouveautés, mais que les discussions qui en découlent se déroulent dans les espaces déjà habituels pour ces sujets.

**Comment by ThibautGery** [comment]
Merci @Canop pour le retour, je pense que mettre un chat/forum est assez couteux couteux à maintenir (infra) et à modérer mais on peut ouvrir une catégorie sur le forum d'Etatlab. Une newsletter est intéressant mais il faudra écrire les mails (et ça va prendre du temps)
Le plus simple étant un flux RSS, ça fait très bien avec Jekyll.
@MattiSG Quel était le coup d'implémenter la newsletter sur [beta.gouv](beta.gouv.fr) ?

**Comment by MattiSG** [comment]
> Quel était le coût d'implémenter la newsletter sur beta.gouv ?

Moyen. Tout est sur sgmap/beta.gouv.fr#183. Mais on a justement déminé pas mal à cet endroit-là, tu peux récupérer ce qu'on a fait (choix du service, éléments à ajouter). Je peux t'aider.

Le problème du RSS, c'est que très peu de gens l'utilisent depuis que les navigateurs ont retiré le support natif, et personne au-delà des geeks, qui ne sont pas la totalité de la cible.

**Comment by MattiSG** [comment]
@ThibautGery Il me semble que tu avais souhaité te connecter au compte Mailjet. Où en est-on ? As-tu besoin d'aide pour dupliquer la fonctionnalité depuis sgmap/beta.gouv.fr ?

**Comment by Morendil** [comment]
Je ferme pour carence de bande passante.
