### ISSUE TITLE
Ajouter une procédure de demande d'API par les consommateurs potentiels

### ISSUE THREAD

**Issue by juliencarnot** [betagouv/api.gouv.fr#127]
Sauf erreur de ma part, pour l'instant il est possible pour une administration d'ajouter une API existante, mais il n'y a pas de guidelines pour solliciter la mise à dispo d'une API pour quelqu'un qui n'aurait pas trouvé son bonheur dans la liste.

Use case:
- Je découvre le site api.gouv.fr en cherchant une API spécifique pour enrichir mon service
- Je consulte la liste des API déjà dispo
- Il n'y a pas ce qu'il me faut
- Au lieu de fermer l'onglet et d'oublier api.gouv.fr pour un moment, je peux exprimer mon besoin (par exemple en créant une issue GitHub avec un [template défini](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) )
- l'équipe d'api.gouv.fr peut évaluer/transmettre la demande et ainsi identifier des nouveaux gisements de valeur
- d'autres consommateurs potentiels de l'API peuvent trouver le ticket et confirmer la demande par un commentaire ou par un subscribe ou avoir l'explication du pourquoi c'est pas encore dispo ou pourquoi ça ne le sera pas...

**Comment by MattiSG** [comment]
Bonjour @juliencarnot, et merci pour cette suggestion.

Le point est que nous n'avons aujourd'hui aucun moyen de garantir l'éventuelle ouverture des API qui seront demandées. Il faut donc que nous trouvions comment convertir ces demandes en une puissance qui permette à terme d'accompagner leur ouverture.

Nous pouvons tout à fait accumuler des demandes à coût minime, mais je crains que cela ne soit frustrant pour les demandeurs (« ça fait un an que j'avais demandé, et toujours rien, c'est nul ! »).

En tant que demandeur, quels disclaimers te sembleraient acceptables pour que tu prennes le temps de faire une demande, sans pour autant te sentir frustré si rien ne peut être fait dans des délais raisonnables ?
Inversement, une solution telle que le [forum Étalab](https://forum.etalab.gouv.fr) ne répondrait-elle pas à ton besoin, au sens où elle te permettrait d'échanger avec d'autres personnes et de trouver des solutions alternatives ?

**Comment by juliencarnot** [comment]
Merci pour la réponse @MattiSG !

J'ai l'impression que le visiteur d' api.gouv.fr qui irait sur une page de guidelines pour soumettre une idée serait bien souvent déjà conscient que vos moyens (et ceux des autres administrations) ne sont pas illimités et que l'administration a le droit d'avoir une stratégie de développement et de déploiement qui ne corresponde pas forcément à ses desiderata, mais en effet, ça va toujours mieux en le disant.

Ça peut même être l'occasion de présenter votre démarche et vos critères de priorisation pour les API déjà sorties (impact de la dispo de l'API pour tel public, faisabilité technique, coût de mise en œuvre et de maintenance, etc.). À mon sens, si vous vous engagez à faire une première réponse sous une quinzaine de jours pour partager une première évaluation de la demande sur ces critères (sans engagement sur un calendrier de mise à dispo), le demandeur ne sera pas frustré très longtemps. Il pourra partager votre analyse ou non, mais il a posé la question et eu une réponse.

Sur la solution technique, pas de préférence, ça peut être des issues Github ou des posts sur le forum étalab, ce qui sera le plus simple à soumettre, trier et lire, commenter et conserver (il y aura des demandes rejetées et d'autres en doublon...)!

**Comment by MattiSG** [comment]
Ok, intéressant. Merci beaucoup pour cette réponse détaillée. Il faut qu'on voie si le coût de traitement de ces requêtes est gérable. Le sujet est que ce n'est pas nous qui allons créer ou ouvrir toutes ces API, donc prendre le temps d'identifier l'administration et le service correspondants permet de donner une réponse à la demande, mais ne garantit pas d'augmenter les chances d'ouvrir l'API correspondante.

Pour l'instant, la « procédure » est celle indiquée [dans la page contact](https://github.com/sgmap/api.gouv.fr/blob/1fd1f34018db155c1d000c6c8b944a0e4da649ca/contact.md#demande-de-nouvelles-api) :

> Contactez directement l'organisme qui produit la donnée ou le service auquel vous souhaiteriez accéder. Vous pouvez nous informer de votre démarche et nous tenterons de vous aider, mais nous n'avons pas d'autorité pour forcer l'ouverture d'API.

Il me semblerait pertinent d'attendre d'avoir des sollicitations avant d'outiller cette interaction spécifique.

@ThibautGery A-t-on déjà reçu des demandes d'ouverture d'API supplémentaires ? Si oui, lesquelles et de la part de qui ?

**Comment by juliencarnot** [comment]
Bien cette info dans la page contact! 

Pour diminuer le coût de traitement des demandes, vous pouvez peut-être imaginer de demander au demandeur de bien les qualifier (avec un [template d'issue](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) par exemple?): le demandeur connaîtra probablement le producteur/l'opérateur cible et pourra participer à votre analyse en expliquant pourquoi sa demande répond à vos critères de sélection? 

Dans certains cas, votre intervention sera peut-être limitée: entre une demande bien formulée et une ou deux réactions de tiers pour compléter le besoin ou les alternatives, voire le retour du producteur/opérateur, il n'y aura pas besoin d'y passer des heures... La multitude peut vous aider vous aussi! ;-) À mon sens, c'est publier et partager la demande qui peut révéler son potentiel et augmenter ses chances d'aboutir.

Dernier point sur la procédure actuelle: il n'est pas sûr que le demandeur pense à mentionner api.gouv.fr au producteur/opérateur, et il n'est pas absolument certain que la personne qui va répondre soit très au fait de l'État-plateforme et de la possibilité d'un accompagnement ou même d'une visibilité sur api.gouv.fr...

Merci de votre écoute en tous cas!

**Comment by MattiSG** [comment]
Je t'en prie, ce n'est pas de l'écoute mais de la construction commune, et c'est nous qui te remercions pour ces suggestions positives et complètes !

Je vois un lien avec #155 : peut-être pourrait-on mêler demandes par les consommateurs potentiels et annonces par les producteurs, en faisant du catalogue un moyen d'échanger et de co-construire les API… ❤️

**Comment by jdesboeufs** [comment]
Tout à fait d'accord avec cette démarche.

On pourrait utiliser un tag "demande-api", derrière on bénéficie de la
discussion et du mécanisme de réactions pour prendre la température.
Et le jour où on a envie d'afficher ça dans api.gouv.fr, rien de plus
facile.
Le ven. 8 juil. 2016 à 19:07, Matti Schneider <notifications@github.com> a
écrit :

**Comment by juliencarnot** [comment]
Je viens de découvrir [DodoData](http://www.dododata.io) qui apporte une réponse à cette problématique. Il est centré sur les data, mais qui imagine encore une ouverture de data sans ouverture d'API pour les récupérer? ;-)

**Comment by Morendil** [comment]
Je vais fermer cette PR pour les raisons évoquées ailleurs: nous n'avons pas de bande passante réelle à y allouer en ce moment. Par contre je trouve intéressante l'idée de faire le lien avec DodoData, ça ne nous engage qu'à avoir une conversation. @datactivist comment pourrait-on échanger à ce sujet ? Mon mail est dans ma page de profil...
