### ISSUE TITLE
Rendre plus claires les conditions d'acceptation pour les différentes API ouvertes sous contrat

### ISSUE THREAD

**Issue by ThibautGery** [betagouv/api.gouv.fr#152]
## Problème

Nous recevons beaucoup de mail demandant si des entreprises privés peuvent avoir accès aux API Entreprise et Particulier. 
## Solutions

Il doit être possible de lire les conditions derrière les licences `OUVERT sous contrat`

**Comment by patama** [comment]
Proposition : 
Si le fournisseur dispose d'une page où il définit les conditions d'accès à son api, mettre un lien vers cette page directement sous `OUVERT sous contrat`
Si le fournisseur n'en dispose pas, faire pointer `OUVERT sous contrat` vers une page de notre site qui explique ce que signifie `OUVERT sous contrat` et `OUVERT`

**Comment by Morendil** [comment]
Je ferme l'issue, entre autre par manque de bande passante allouée à ce sujets actuellement; il me semble cependant que `page.access_link` devrait remplir ce rôle - la solution proposée pour [API Particulier](https://particulier.api.gouv.fr/charte.html) me semble particulièrement pertinente et elle est postérieure à cette discussion, il me semble qu'elle devrait faire exemple.
