### ISSUE TITLE
Améliorer l'accessibilité du site

### ISSUE THREAD

**Issue by ThibautGery** [betagouv/api.gouv.fr#154]
Retour par mail :
- Il faudrait ajouter l’attribut lang=’fr’ sur l’élément html (sinon la vocalisation des pages avec les lecteurs d’écran se fait avec la voix anglaise)
- Le champ de recherche n’a pas de label, ni de bouton de validation

Il y a d’autres points d’amélioration pour que le site réponde aux exigences d’accessibilité, je pourrais renvoyer au [RGAA](http://references.modernisation.gouv.fr/rgaa-accessibilite/), mais ce n’est pas le document le plus pédagogique pour entrer dans le sujet.

Je recommanderais plutôt les notices [accede-web](http://www.accede-web.com/notices/) bien plus facile à lire. Par exemple [Html Css Javascript/](http://www.accede-web.com/notices/html-css-javascript/) :
- [http://www.accede-web.com/notices/html-css-javascript/3-langues/3-1-attribut-lang-balise-html/](http://www.accede-web.com/notices/html-css-javascript/3-langues/3-1-attribut-lang-balise-html/)
- [http://www.accede-web.com/notices/html-css-javascript/7-formulaires/7-2-title-aria-label-champs-sans-intitule/](http://www.accede-web.com/notices/html-css-javascript/7-formulaires/7-2-title-aria-label-champs-sans-intitule/)

C’est très bien fait, on trouve de nombreux exemples de code et explications et c’est en français.

**Comment by jdesboeufs** [comment]
@Flightan : est-ce que tu as des préconisations ?

**Comment by mfaure** [comment]
@jdesboeufs tu peux commencer par utiliser [Asqatasun](https://asqatasun.org/), en plus il est dans le SILL (Socle Interministériel de Logiciels Libres). Soit à installer, soit en Docker pour jouer, soit sur la [démo en ligne](https://app.Asqatasun.org)

(disclaimer: j'en suis le créateur)
