### ISSUE TITLE
Fournir un planning de lancement d'API

### ISSUE THREAD

**Issue by ThibautGery** [betagouv/api.gouv.fr#155]
Des retours utilisateurs nous demande quelle est le planning de lancement des différentes API. 

Il faut plus insister sur le caractère disponibles des API

**Comment by patama** [comment]
OK avec toi, c'est une grosse charge à prévoir pour recueillir ces informations, c'est plus simple de rester sur la philosophie "seulement les api en prod".
En fait, lors des openlabs fin 2015, les personnes souhaitaient connaitre deux choses : 
D'une part, les prochaines api qui arrivent d'ici 3 ou 6 mois, c'est l'idée de roadmap globale Etat Plateforme, idée que tu soulignes ici.
Et d'autre part, pour une api donnée, connaitre les prochaines évolutions prévues
C'est surement plus simple et plus maintenable de réfléchir à un endroit où le producteur de l'api indique ses prochaines évolutions ?

**Comment by MattiSG** [comment]
Duplicate of #78 ?

**Comment by patama** [comment]
Pas forcément un doublon.
La demande initiale est de connaitre à l'avance le planning des api qui arriveront en production dans un futur proche, donc même pas encore expérimentales.

**Comment by MattiSG** [comment]
Ok, et la réponse est : non, pas de planning car « seulement les API en prod sont listées », on est bien d'accord ?

**Comment by jdesboeufs** [comment]
Pour ce qui est des API en production, peut-être ajouter une méta qui permette d'avoir un lien vers une sorte de CHANGELOG (que chaque producteur peut éditorialiser comme il l'entend), ainsi qu'un canal d'inscription mailing-list (toujours optionnel).

Pour GéoAPI on est preneur des deux.

**Comment by patama** [comment]
Encore une fois, il y a deux sujets : 
1. le producteur de l'api veut informer sur ses prochaines évolutions
2. un producteur veut informer de sa future api qui arrivera dans X années

pour le 1. -> je verrai bien un lien vers une roadmap sur le site du producteur, s'il en a une, edito a sa main comme le dit jerome
 
pour le 2. -> on a dit que l'on ne catalogue que les api de prod,  mais on peut peut etre mettre une page Roadmap EtatPlateforme quelque part sur le site, (mais comment la gérer, qui alimente / qui valide) ca me semble compliqué ...

**Comment by MattiSG** [comment]
> 1. le producteur de l'api veut informer sur ses prochaines évolutions

Il a la main sur le texte libre. Si on en a beaucoup qui mettent des liens vers une telle page, on verra pour uniformiser. Laissons venir.

> 2. un producteur veut informer de sa future api qui arrivera dans X années

On va forcément être vus comme responsables de cette roadmap. On ne peut pas prendre d'engagement pour les autres, donc à mon avis on ne fait rien tant qu'on n'a pas de moyen de suivre et d'appuyer l'ouverture d'API.

**Comment by patama** [comment]
J'aime bcp le pendant pour que le consommateur demande des api ou des évolutions #127 .

Pour les évolutions dans le texte libre, je pense que cela modifie l'intention de l'onglet 'description'. Je propose plutot l'ajout d'un onglet facultatif, par exemple 'évolutions à venir' où le producteur peut decrire les évolutions de son api. ca me semble couvrir le besoin à moindre cout.

Ok avec toi pour la responsabiltié de la roadmap des api, discussion à poursuivre. quand la dynamique sera là.

**Comment by Morendil** [comment]
Je ferme dans l'attente de circonstances qui referaient de cette question une priorité.
