### ISSUE TITLE
Feature Request: Api barème kilométriques

### ISSUE THREAD

**Issue by dolibarr95** [betagouv/api.gouv.fr#228]
Bonjour
Il serait bien que l'on puisse consulter via votre api les barèmes de frais kilométriques.
Différents paramètres serait alors disponibles

- annee
- cv
- km

et des requêtes du type
```php
https://api.gouv.fr/api/bareme?annee=2015&cv=5
```
avec en reponse un peu du genre 
```json 
{ 
     "status":"ok",
     "anne": 2005,
     "cv": 5,
     "km" : [
                    { "0": "0,245" , "plus" :"0" },
                    { "5001": "0,245" , "plus" :"824" },
                    { "20000": "0,286" , "plus" :"0" }
               ]
   
 }
```
Merci

**Comment by Morendil** [comment]
Merci pour cette suggestion. Une telle API aurait de la valeur, indéniablement.

Le catalogue api.gouv.fr a vocation à répertorier les API existantes, plutôt qu'à être lui-même un point central d'implémentation de *endpoints* spécifiques; nous traitons les demandes de référencement au fil de l’eau, comme celles de Pôle Emploi ou Hub’Eau actuellement, en fonction des travaux des administrations qui les mettent en oeuvre.

Nous ne sommes pas pour l’instant outillés convenablement pour recueillir et soutenir des demandes d’ouvertures d’API adressées à des administrations, qu’elles soient ou non nommément identifiées, mais nous intégrons cette question dans nos réflexions (cf #127).

En attendant, nous gardons bien entendu la trace de votre proposition et ne manquerons pas de vous faire signe si cette API devient disponible.
