### ISSUE TITLE
Ajout des données du journal officiel dans l'api gouv

### ISSUE THREAD

**Issue by XCarle** [betagouv/api.gouv.fr#230]
Une API des données de http://www.journal-officiel.gouv.fr/ permettrait aux acteurs des différents secteurs concernés de se mettre à jour automatiquement.

**Comment by Morendil** [comment]
Merci pour cette suggestion. Une telle API aurait de la valeur, indéniablement.

Le catalogue api.gouv.fr a vocation à répertorier les API existantes; nous traitons les demandes de référencement au fil de l’eau, comme celles de Pôle Emploi ou Hub’Eau actuellement, en fonction des travaux des administrations qui les mettent en oeuvre.

Nous ne sommes pas pour l’instant outillés convenablement pour recueillir et soutenir des demandes d’ouvertures d’API adressées à des administrations, qu’elles soient ou non nommément identifiées, mais nous intégrons cette question dans nos réflexions (cf #127).

En attendant, nous gardons bien entendu la trace de votre proposition et ne manquerons pas de vous faire signe si cette API devient disponible.
