### ISSUE TITLE
Référencer les API de data.education.gouv.fr?

### ISSUE THREAD

**Issue by jothoma1** [betagouv/api.gouv.fr#285]
J'utilise les données de https://data.education.gouv.fr/ via les API (notamment pour les collèges). Pourquoi ne pas les référencer dans votre liste des API ?

Bon courage et continuez le travail c'est top !
Johan

**Comment by lucasdcrk** [comment]
Bonne idée

**Comment by rdubigny** [comment]
Bonjour,

Merci pour cette idée. Pouvez vous nous aider en ajoutant une fiche d'API : https://github.com/betagouv/api.gouv.fr/blob/master/CONTRIBUTING.md#ajouter-une-api ?

Merci d'avance.

**Comment by patama** [comment]
Bonjour,
fiche d'API https://api.gouv.fr/api/api_menj.html ajoutée au catalogue.
Merci beaucoup
