### ISSUE TITLE
Amélioration de l'UI des pages fournisseur d'API

### ISSUE THREAD

**Issue by rdubigny** [betagouv/api.gouv.fr#303]
Suite au changement de https://github.com/betagouv/api.gouv.fr/pull/296 . Prendre en compte les retours proposés par https://github.com/betagouv/api.gouv.fr/pull/296#issuecomment-425027060 .

cc. @Morendil

**Comment by etienneCharignon** [comment]
🧢 : je ferme cette issue qui n'est plus d'actualité
