### ISSUE TITLE
Afficher une ancre sur les titres de sections dans la page API

### ISSUE THREAD

**Issue by Flightan** [betagouv/api.gouv.fr#304]
Sur les affichages des README sur github, il est affiché, lors du survol avec la souris, une petite ancre permettant de connaitre le lien direct vers la section actuelle.
Je pense que c'est utile pour trouver le lien rapidement et le partager (ex: voici la partie "Acces" de l'API Particulier.

<img width="438" alt="capture d ecran 2018-09-29 a 10 42 40" src="https://user-images.githubusercontent.com/1475946/46243459-c1ff0980-c3d4-11e8-9a8f-d5d62a1bf81f.png">

**Comment by AntoineAugusti** [comment]
Implémentation dans #362

**Comment by rdubigny** [comment]
fixed in #362
