### ISSUE TITLE
Supprimer la page Simulaire

### ISSUE THREAD

**Issue by djibe** [betagouv/api.gouv.fr#330]
Bonjour,
le simulateur de coût d'embauche ne fonctionne pas : https://www.simulaire.fr/
Mais il ressemble à un doublon de https://embauche.beta.gouv.fr/

Merci de votre aide

**Comment by rdubigny** [comment]
Hello @laem,

Pourriez vous mettre à jour la fiche service https://api.gouv.fr/service/simulaire.html ?

cc. @mquandalle

**Comment by rdubigny** [comment]
https://embauche.beta.gouv.fr/ est déjà référencé dans https://api.gouv.fr/service/simulateur-cout-embauche.html.

Il faut donc supprimer la page [simulaire](https://api.gouv.fr/service/simulaire.html) sur api.gouv.fr.
