### ISSUE TITLE
Mise en place de la CI

### ISSUE THREAD

**Issue by XavierJp** [betagouv/api.gouv.fr#478]
[/] Prettier
[/] WCAG and accessiblity
[] 404 checks
[/] npm audit

**Comment by Morendil** [comment]
Pour WCAG avec quel outil ? Ca m'intéresse pour d'autres produits :)

**Comment by XavierJp** [comment]
@Morendil je découpe en trois phases :

- [Etude du sujet (en cours) ](https://www.notion.so/Accessibilit-2df640a2db8642c195cad8e4776cb43a)
- Implémentation d'un ou plusieurs outils de CI pour auditer le code (validité du HTML, CSS)
- Mise en place d'un protocole d'audit du site une fois en ligne (typiquement sur la couleur, le contraste, etc.)

Sur l'audit de code j'utilise déjà ```eslint-plugin-jsx-a11y```et je regarde ```react-axe``` (audit de code donc forcément spécifique de la techno)
Sur l'aspect audit du site en ligne je n'ai pas encore d'idée, mais pas mal de [pistes](https://a11yproject.com/resources/)

Qu'en penses-tu ?

**Comment by XavierJp** [comment]
@Morendil finalement je vais :

- utiliser le linter pour auditer la qualité & accessibilité du code (cette partie est techno spécifique)
- utiliser axe-cli dans la ci qui va parser la sitemap et tester a chaque déploiement l'accessiblité de toutes les pages. Cette partie est techno agnostique
- utiliser un link checker et parser la sitemap pour faire remonter tous les liens cassés
