### ISSUE TITLE
Supprimer le lien de bas de page cassé

### ISSUE THREAD

**Issue by jdauphant** [betagouv/api.gouv.fr#497]
![image](https://user-images.githubusercontent.com/1238254/76085866-2acbb780-5fb3-11ea-83c8-468d3b521ed9.png)

Je crois que https://etatplateforme.modernisation.gouv.fr/ n'existe plus

**Comment by XavierJp** [comment]
@jdauphant @romtal pensez vous qu'on supprime ce lien ou bien est ce qu'on redirige ailleurs ?

**Comment by romtal** [comment]
On peut supprimerEnvoyé depuis mon téléphone Huawei-------- Message original --------De : XavierJp <notifications@github.com>Date : ven. 6 mars 2020 à 14:40À : "betagouv/api.gouv.fr" <api.gouv.fr@noreply.github.com>Cc : romtal <romaintales9@gmail.com>, Mention <mention@noreply.github.com>Objet : Re: [betagouv/api.gouv.fr] Le lien de bas de page d'état plateforme est mort (#497)@jdauphant @romtal pensez vous qu'on supprime ce lien ou bien est ce qu'on redirige ailleurs ?

**Comment by XavierJp** [comment]
D'accord. j'ai passé cette issue sur le projet `Bugs`

**Comment by romtal** [comment]
👌Envoyé depuis mon téléphone Huawei-------- Message original --------De : XavierJp <notifications@github.com>Date : ven. 6 mars 2020 à 14:52À : "betagouv/api.gouv.fr" <api.gouv.fr@noreply.github.com>Cc : romtal <romaintales9@gmail.com>, Mention <mention@noreply.github.com>Objet : Re: [betagouv/api.gouv.fr] Le lien de bas de page d'état plateforme est mort (#497)D'accord. j'ai passé cette issue sur le projet Bugs
