### ISSUE TITLE
le filtre thématique de la recherche d'API ne fonctionne plus

### ISSUE THREAD

**Issue by romtal** [betagouv/api.gouv.fr#518]
![image](https://user-images.githubusercontent.com/15154033/80120504-67676880-858b-11ea-91a1-93b72abb497c.png)
![image](https://user-images.githubusercontent.com/15154033/80120517-6afaef80-858b-11ea-8084-ffe42d90d5ad.png)

Erreur: 
TypeError: "t.themes is undefined"
    NextJS 12
commons.668bd467df88e830a259.js:1:301693

**Comment by XavierJp** [comment]
Merci @Romain, Erreur bien identifiée et en cours de résolution !

**Comment by XavierJp** [comment]
closed by #520
