### ISSUE TITLE
Uniformisation des CGU

### ISSUE THREAD

**Issue by ThibautGery** [betagouv/api.gouv.fr#55]
S'inspirer de [tldrlegal.com](https://tldrlegal.com/license/mit-license) pour proposer une simplification des CGU

**Comment by MattiSG** [comment]
Voir le travail important (notamment dans le contexte français et plus encore administratif) de @tsaintaubin d'OpenLaw sur un [référentiel de CGU](http://openlaw.fr/index.php?title=Référentiel_de_CGU) : [tsaintaubin/referentiel_cgu](https://github.com/tsaintaubin/referentiel_cgu).

Pour ce qui est de la représentation (un des succès des CC), voir le [travail d'Aza Raskin](http://www.azarask.in/blog/post/privacy-icons/) sur les [Privacy Icons](https://wiki.mozilla.org/Privacy_Icons).

**Comment by MattiSG** [comment]
Duplicate of #152 ?

**Comment by MattiSG** [comment]
> Duplicate of #152 ?

Non, pas tout à fait. Résoudre #55 résoudrait #152, mais on peut résoudre #152 sans résoudre #55.

**Comment by Morendil** [comment]
Je ferme pour refléter l'absence de bande passante consacrée à cette issue.
