### ISSUE TITLE
développeur.api.gouv.fr n'existe pas

### ISSUE THREAD

**Issue by bzg** [betagouv/api.gouv.fr#551]
L'image ci-dessous suggère l'existence d'une URL `développeur.api.gouv.fr` qui n'existe pas.

![2020-06-15-155302_1920x1080_scrot](https://user-images.githubusercontent.com/63500/84665644-5bab7900-af20-11ea-9e93-0b2fa793c682.png)

Peut-être simplement utiliser une autre URL ou un autre nom ici?

**Comment by XavierJp** [comment]
Hello @bzg, merci d'avoir fait remonter le sujet.

On peut aussi envisager de rediriger `developpeur.api.gouv.fr` sur `api.gouv.fr/documentation`
Est ce que tu vois une raison pour préférer un autre URL ou un autre nom ?

Sur un autre sujet, la search bar ne s'affiche pas correctement, quel OS/browser utilise-tu ?

**Comment by bzg** [comment]
Merci @XavierJp pour la réponse.

En fait, je ne comprends pas le nom du tout : j'ai l'impression qu'il s'agit de l'espace de documentation d'`api.gouv.fr`, donc un titre disant "Documentation d'api.gouv.fr" me paraît plus direct.  

Une URL est redondante : je sais que c'est une sorte de norme qu'on trouve un peu partout (https://beta.gouv.fr, https://data.gouv.fr, https://code.etalab.gouv.fr...) mais je ne crois pas que ce soit une obligation et si c'est une norme, elle me paraît absurde. Je vais poser la question à la com' pour comprendre.  S'il _faut_ absolument une URL, je mettrais alors `api.gouv.fr` en ajoutant un titre quelque part pour dire qu'il s'agit de la documentation.

> Sur un autre sujet, la search bar ne s'affiche pas correctement, quel OS/browser utilise-tu ?

Firefox 77.0.1 (64 bits) sur Ubuntu 20.04.

**Comment by bzg** [comment]
Une idée serait de remplacer `développeur.api.gouv.fr` par `api.gouv.fr` et d'accoler "Documentation technique" (ou "Documentation de référence) à côté d'`api.gouv.fr`.

**Comment by XavierJp** [comment]
@bzg  je propose les modifs suivantes : #556

**Comment by bzg** [comment]
LGTM, modulo le point médian :)
