### ISSUE TITLE
swagger en local

### ISSUE THREAD

**Issue by mogador26** [betagouv/api.gouv.fr#587]
Avoir la possibilité de référencer localement le swagger d'une API.
suggestion: ajouter un paramètre  doc_tech_local dans le fichier markdown de description de l'API

**Comment by XavierJp** [comment]
Bonjour @mogador26 

Merci d'avoir crée cette issue, est-ce que vous pouvez préciser s'il vous plait ce que vous entendez par référencer localement le swagger d'une API ? 

Aujourd'hui `doc_tech_link` permet de référencer un swagger qui s'affichera ensuite dans la page des documentations : 
par exemple : https://api.gouv.fr/documentation/api-particulier

Et `doc_tech_external` permet de réferencer une documentation située sur un site internet dédié comme par exemple  https://api.gouv.fr/documentation/franceconnect

**Comment by mogador26** [comment]
Voici les précisions : une API dispose d'un swagger. La swagger (yaml ou json) n'est malheureusement pas accessible depuis un site internet, ma question est : où est-il possible de déposer le swagger pour le rendre accessible ?

**Comment by XavierJp** [comment]
Bonjour,

Jusqu'ici, le besoin ne s'était pas encore fait sentir, et nous encourageons vivement les producteurs d’APIs à exposer un swagger (même si cela doit être la seule route accessible depuis internet)

Mais si vous souhaitez référencer une API pour laquelle cela s'appliquerait, nous pouvons faire évoluer le code

**Comment by mogador26** [comment]
Merci pour votre réponse. 
Effectivement la demande peut paraitre insolite mais elle permettrait de traiter le cas d'usage d'un fournisseur d'api ne disposant que d'un fichier swagger pour référencer la description de son api.

**Comment by XavierJp** [comment]
Bonjour, 

Quel est le fournisseur / l'API concernée ? Je serais intéresse par faire une réunion sur le sujet et l'approfondir.

**Comment by mogador26** [comment]
Bonjour,

Quel canal pouvons nous utiliser pour pouvoir échanger  ?

Par avance merci.

**Comment by XavierJp** [comment]
Bonjour, 
Je vous propose de faire une visio sur [cette plateforme ](https://visio.incubateur.net/b/xav-a2x-cd6)
Est ce que Lundi ou Mardi à 14h vous conviendrait ?

**Comment by XavierJp** [comment]
Si vous avez un mail sur lequel je peux vous joindre je peux vous envoyer une invitation. Vous pouvez aussi me joindre a xavier.jouppe@beta.gouv.fr

**Comment by XavierJp** [comment]
Bonjour, 

C'est désormais possible d'intégrer un swagger en local. Dans le code actuel nous avons deux exemples de swaggers ainsi exposés : 

`
http://api.gouv.fr/swaggers/api-impot-particulier.yaml
http://api.gouv.fr/swaggers/api-r2p.json
`
Les swaggers sont exposables directement dans `/public/swaggers`

**Comment by mogador26** [comment]
Bonjour Xavier,
Parfait merci cela fonctionne.
