### ISSUE TITLE
Le HTML n'est pas interprété dans les clés rate_limiting_description et monitoring_description des fiches API

### ISSUE THREAD

**Issue by skelz0r** [betagouv/api.gouv.fr#601]
Exemple : https://api.gouv.fr/les-api/api_ameli_droits_cnam (screenshot ci-dessous) (fichier: https://github.com/betagouv/api.gouv.fr/blob/master/_data/api/api_ameli_droits_cnam.md )

<img width="381" alt="Screen Shot 2020-09-14 at 13 52 21" src="https://user-images.githubusercontent.com/1279968/93082622-89c06680-f691-11ea-9d17-8695d976b965.png">

Les clés concernées sont les suivantes: `rate_limiting_description` et `monitoring_description`

**Comment by XavierJp** [comment]
Hello @skelz0r effectivement, c'est voulu, les balises `<p>` à cet endroit ne servent pas, donc la solution slon moi serait plutot de les retirer du texte.

**Comment by XavierJp** [comment]
J'ai retiré les derniers <p> qui restaient. Ils remontent à une version différente de la page API que nous avons changée cet été
