### ISSUE TITLE
Unable to render this definition, Please indicate a valid Swagger or OpenAPI version field. 

### ISSUE THREAD

**Issue by jean-francois-labbe** [betagouv/api.gouv.fr#685]
Bonjour la documentation de https://api.gouv.fr/documentation/api_professionnels_rge affiche une erreur.

![Screenshot_2021-04-12_14-58-11](https://user-images.githubusercontent.com/1558372/114398002-93666a00-9b9f-11eb-9ea4-38a596bf1931.png)

**Comment by XavierJp** [comment]
Bonjour @jean-francois-labbe 

J'ai fait remonté ce problème a l'équipe de @Koumoul qui gère le portail open data de l'Ademe, malheureusement, ils utilisent le standard 3.1.x qui n'est pas actuellement supporté par swagger-ui :
 https://github.com/swagger-api/swagger-ui/issues/5891

Pour pallier a cet inconvénient, je vais rendre le lien vers leur portail disponible, vous y retrouverez la documentation

**Comment by XavierJp** [comment]
J'ai ajouté un lien sur https://api.gouv.fr/documentation/api_professionnels_rge, c'est un fix temporaire en attendant la maj de swagger-ui.

**Comment by XavierJp** [comment]
@jean-francois-labbe les équipes de Koumoul ont fait le nécessaire pour réparer ce comportement. Je ferme donc cette issue. 

Merci encore pour vos retours.
