### ISSUE TITLE
Api gouv ne répond pus

### ISSUE THREAD

**Issue by Olivier4477** [betagouv/api.gouv.fr#717]
Bonjour, 

L'api du gouv ne répond plus aujourd'hui:

NET::ERR_CERT_DATE_INVALID

merci

**Comment by XavierJp** [comment]
Bonjour @Olivier4477 

Pouvez vous préciser quelle API, quel url ne répond plus pour nous aider a reproduire le bug s'il vous plait ? 

Merci

**Comment by Olivier4477** [comment]
Je suis collaborateur du projet vitemadose
Visiblement c'est l'url suivante: https://geo.api.gouv.fr/communes?nom=Paris&fields=codesPostaux,centre,departement&limit=15

ajourd'hui visiblement cela fonctionne

**Comment by XavierJp** [comment]
Bonjour, 

Cette pane était du à un dysfonctionnement interne a l'API geo. A priori tout doit être revenu a la normale. Je vais donc clore cette issue. 

Merci pour votre message.
