### ISSUE TITLE
Terme Stable versus expérimental

### ISSUE THREAD

**Issue by ThibautGery** [betagouv/api.gouv.fr#78]
Pas bien compris

**Comment by patama** [comment]
Effectivement, le terme expérimental est mal compris,
il faudrait simplement expliciter qu'on peut bien sur construire un service grace à une api "expérimentale" mais que l'interface peut changer à tout moment -> pas de garantie de la part du fournisseur sur la stabilité de l'API

**Comment by MattiSG** [comment]
Sous-ensemble de #55.

**Comment by Morendil** [comment]
Je ferme pour absence de bande passante.
