### ISSUE TITLE
Contribuer à github.com/public-apis/public-apis ?

### ISSUE THREAD

**Issue by bzg** [betagouv/api.gouv.fr#815]
https://github.com/public-apis/public-apis a pas mal d'étoiles, environ 164K.

Est-ce que cela pourrait être pertinent, si ce n'est pas trop compliqué, de tenter d'y référencer les API ouvertes déjà listées sur api.gouv.fr?

Ca permettrait peut-être d'atteindre de plus nombreux réutilisateurs hors de l'administration? 

2cts!

**Comment by etienne0101** [comment]
J'ai tenté une pull request pour ajouter api.gouv.fr sur Public API, mais on m'a indiqué que le projet était en stand by https://github.com/public-apis/public-apis/issues/3104

**Comment by bzg** [comment]
Gouvernance, gouvernance... dommage, mais merci d'avoir tenté !
