### ISSUE TITLE
Répétition de texte dans la page guide "Tarification de la restauration scolaire et des activités périscolaires et municipales"

### ISSUE THREAD

**Issue by mathildehg** [betagouv/api.gouv.fr#827]
Il y a une répétition de deux paragraphes à la fin de la page  :
" Pour remplir votre demande, vous aurez besoin :
    de votre numéro SIRET
    du cadre juridique
    de la description du service justifiant une simplification pour les citoyens
    des coordonnées de l'équipe
    des coordonnées de votre délégué à la protection des données et responsable de traitement"

Pourtant, le markdown de la page semble correct : https://github.com/betagouv/api.gouv.fr/blob/master/_data/guides/portail-famille-tarification.md

![Capture d’écran 2021-11-08 à 17 27 27](https://user-images.githubusercontent.com/45592821/140780143-42df5cde-aaa9-4ead-9b0c-203cb9a27dac.png)

**Comment by mathildehg** [comment]
@etienne0101

**Comment by etienne0101** [comment]
@mathildehg C'est en cours de correction :-)
En fait le bouton next steps reprend déjà ce texte, donc il était en doublon. 
https://github.com/betagouv/api.gouv.fr/pull/829

**Comment by mathildehg** [comment]
Parfait ! merci :)

**Comment by XavierJp** [comment]
Fixed #829
