### ISSUE TITLE
typo : https://api.gouv.fr/les-api/api-particulier

### ISSUE THREAD

**Issue by mfo** [betagouv/api.gouv.fr#946]
automatiser l'instruction des demandes ?
<img width="409" alt="Screen Shot 2022-04-05 at 3 26 21 PM" src="https://user-images.githubusercontent.com/125964/161764240-ddf61c36-9bde-45dc-bf50-f026f42315da.png">
,

**Comment by etienne0101** [comment]
Bien vu, merci ! https://github.com/betagouv/api.gouv.fr/pull/947
