### ISSUE TITLE
Suppression de l'API Sirene données ouvertes

### ISSUE THREAD

**Issue by johanricher** [betagouv/api.gouv.fr#983]
L'API "Sirene données ouvertes", mentionnée sur la page [Quelle API Sirene utiliser ?](https://github.com/betagouv/api.gouv.fr/blob/master/_data/guides/quelle-api-sirene.md) du site api.gouv.fr, n'existe plus. La page devrait être mise à jour.

**Comment by XavierJp** [comment]
Fix en cours de déploiement ! Merci
